/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bitacora.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

char **
add_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	time_t timeres = time(NULL);
	
	FILE *f = fopen("file.txt", "a+"); 
	if (f == NULL) {
    printf("Error opening file!\n");
    exit(1);
	}
	char * time = asctime(localtime(&timeres));
	
	fprintf(f, "%s %s", *argp, time);
	printf("Server Added:%s %s", *argp, time);
	fclose(f);
	
	asprintf(&result, "%s %s", *argp, time);
	
	return &result;
}

char **
search_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	printf("Server is searching for: %s \n", *argp);
	
	FILE* fh = fopen("file.txt", "r");
	//check if file exists
	if (fh == NULL){
    printf("file does not exists");
    return 0;
	}
 	char buff[1000];
  	char *s;
	//read line by line
	
	const size_t line_size = 300;
	char* line = malloc(line_size);
	int count = 0;
	while (fgets(line, line_size, fh) != NULL){
  	//printf("%s",line);
  	
  	s = strstr(line, *argp);
 		if (s != NULL) {
     count++;
    }
    else {
			//printf("String not found\n");
 		}
	}
	
  	printf("Registry found: %d times \n", count);
	asprintf(&result, "Server Found, %s %d times", *argp, count);
	
	return &result;
}
