/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, int opt, char *name)
{
	CLIENT *clnt;
	char * *result_1;
	char * add_1_arg;
	char * *result_2;
	char * search_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(opt==1){
		add_1_arg = name;
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (char **) NULL) {
			//clnt_perror (clnt, "call failed");
		} else {
			printf("Server response: %s", *result_1);
		}
	}
	
	if(opt==2){
		search_1_arg = name;
		result_2 = search_1(&search_1_arg, clnt);
		if (result_2 == (char **) NULL) {
			//clnt_perror (clnt, "call failed");
		} else {
			printf("Server response: %s \n", *result_2);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main(int argc, char *argv[]) {
        char *host;
        char *name;
        int id, opt;
        if (argc != 4) {
            printf ("usage: %s host opt name\n", argv[0]);
            exit(1);
        }
        host = argv[1]; // Host.
        name = argv[3];
        // opt
        if ((opt = atoi(argv[2])) == 0 && *argv[2] != '0') {
            fprintf(stderr, "invalid value: %s\n", argv[2]);
            exit(1);
        }
        add_prog_1(host, opt, name);
}
